[2019-01-02 00:02:24 +0000] [9933] [INFO] Starting gunicorn 19.9.0
[2019-01-02 00:02:24 +0000] [9933] [INFO] Listening at: http://127.0.0.1:8000 (9933)
[2019-01-02 00:02:24 +0000] [9933] [INFO] Using worker: sync
[2019-01-02 00:02:24 +0000] [9937] [INFO] Booting worker with pid: 9937
[2019-01-02 00:49:53 +0000] [9933] [INFO] Handling signal: term
[2019-01-02 00:49:53 +0000] [9937] [INFO] Worker exiting (pid: 9937)
[2019-01-02 00:49:53 +0000] [9933] [INFO] Shutting down: Master
[2019-01-02 00:50:01 +0000] [10034] [INFO] Starting gunicorn 19.9.0
[2019-01-02 00:50:01 +0000] [10034] [INFO] Listening at: http://127.0.0.1:8000 (10034)
[2019-01-02 00:50:01 +0000] [10034] [INFO] Using worker: sync
[2019-01-02 00:50:01 +0000] [10038] [INFO] Booting worker with pid: 10038
[2019-01-02 00:50:23 +0000] [10034] [INFO] Handling signal: term
[2019-01-02 00:50:23 +0000] [10038] [INFO] Worker exiting (pid: 10038)
[2019-01-02 00:50:23 +0000] [10034] [INFO] Shutting down: Master
[2019-01-02 00:50:28 +0000] [10069] [INFO] Starting gunicorn 19.9.0
[2019-01-02 00:50:28 +0000] [10069] [INFO] Listening at: http://127.0.0.1:8000 (10069)
[2019-01-02 00:50:28 +0000] [10069] [INFO] Using worker: sync
[2019-01-02 00:50:28 +0000] [10073] [INFO] Booting worker with pid: 10073
[2019-01-02 01:41:45 +0000] [10073] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 01:41:55 +0000] [10073] [INFO] Worker exiting (pid: 10073)
[2019-01-02 01:41:55 +0000] [10172] [INFO] Booting worker with pid: 10172
[2019-01-02 01:41:55 +0000] [10172] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 17, in <module>
    db = SQLALCHEMY(app)
NameError: name 'SQLALCHEMY' is not defined
[2019-01-02 01:41:55 +0000] [10172] [INFO] Worker exiting (pid: 10172)
[2019-01-02 01:41:55 +0000] [10069] [INFO] Shutting down: Master
[2019-01-02 01:41:55 +0000] [10069] [INFO] Reason: Worker failed to boot.
[2019-01-02 08:14:23 +0000] [27103] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:14:23 +0000] [27103] [INFO] Listening at: http://127.0.0.1:8000 (27103)
[2019-01-02 08:14:23 +0000] [27103] [INFO] Using worker: sync
[2019-01-02 08:14:23 +0000] [27107] [INFO] Booting worker with pid: 27107
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:23:31 +0000] [27103] [INFO] Handling signal: term
[2019-01-02 08:23:31 +0000] [27107] [INFO] Worker exiting (pid: 27107)
[2019-01-02 08:23:31 +0000] [27103] [INFO] Shutting down: Master
[2019-01-02 08:23:36 +0000] [27127] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:23:36 +0000] [27127] [INFO] Listening at: http://127.0.0.1:8000 (27127)
[2019-01-02 08:23:36 +0000] [27127] [INFO] Using worker: sync
[2019-01-02 08:23:36 +0000] [27131] [INFO] Booting worker with pid: 27131
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:24:24 +0000] [27136] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:24:24 +0000] [27136] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-02 08:24:24 +0000] [27136] [ERROR] Retrying in 1 second.
[2019-01-02 08:24:25 +0000] [27136] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-02 08:24:25 +0000] [27136] [ERROR] Retrying in 1 second.
[2019-01-02 08:24:26 +0000] [27136] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-02 08:24:26 +0000] [27136] [ERROR] Retrying in 1 second.
[2019-01-02 08:24:27 +0000] [27136] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-02 08:24:27 +0000] [27136] [ERROR] Retrying in 1 second.
[2019-01-02 08:24:28 +0000] [27136] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-02 08:24:28 +0000] [27136] [ERROR] Retrying in 1 second.
[2019-01-02 08:24:29 +0000] [27136] [ERROR] Can't connect to ('localhost', 8000)
[2019-01-02 08:24:34 +0000] [27127] [INFO] Handling signal: term
[2019-01-02 08:24:34 +0000] [27131] [INFO] Worker exiting (pid: 27131)
[2019-01-02 08:24:34 +0000] [27127] [INFO] Shutting down: Master
[2019-01-02 08:24:39 +0000] [27143] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:24:39 +0000] [27143] [INFO] Listening at: http://127.0.0.1:8000 (27143)
[2019-01-02 08:24:39 +0000] [27143] [INFO] Using worker: sync
[2019-01-02 08:24:39 +0000] [27147] [INFO] Booting worker with pid: 27147
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:25:49 +0000] [27143] [INFO] Handling signal: term
[2019-01-02 08:25:49 +0000] [27147] [INFO] Worker exiting (pid: 27147)
[2019-01-02 08:25:49 +0000] [27143] [INFO] Shutting down: Master
[2019-01-02 08:25:49 +0000] [27173] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:25:49 +0000] [27173] [INFO] Listening at: http://127.0.0.1:8000 (27173)
[2019-01-02 08:25:49 +0000] [27173] [INFO] Using worker: sync
[2019-01-02 08:25:49 +0000] [27177] [INFO] Booting worker with pid: 27177
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:26:28 +0000] [27173] [INFO] Handling signal: term
[2019-01-02 08:26:28 +0000] [27177] [INFO] Worker exiting (pid: 27177)
[2019-01-02 08:26:28 +0000] [27173] [INFO] Shutting down: Master
[2019-01-02 08:26:28 +0000] [27183] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:26:28 +0000] [27183] [INFO] Listening at: http://127.0.0.1:8000 (27183)
[2019-01-02 08:26:28 +0000] [27183] [INFO] Using worker: sync
[2019-01-02 08:26:28 +0000] [27187] [INFO] Booting worker with pid: 27187
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:27:14 +0000] [27183] [INFO] Handling signal: term
[2019-01-02 08:27:14 +0000] [27187] [INFO] Worker exiting (pid: 27187)
[2019-01-02 08:27:14 +0000] [27183] [INFO] Shutting down: Master
[2019-01-02 08:27:14 +0000] [27192] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:27:14 +0000] [27192] [INFO] Listening at: http://127.0.0.1:8000 (27192)
[2019-01-02 08:27:14 +0000] [27192] [INFO] Using worker: sync
[2019-01-02 08:27:14 +0000] [27196] [INFO] Booting worker with pid: 27196
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:28:28 +0000] [27192] [INFO] Handling signal: term
[2019-01-02 08:28:28 +0000] [27196] [INFO] Worker exiting (pid: 27196)
[2019-01-02 08:28:28 +0000] [27192] [INFO] Shutting down: Master
[2019-01-02 08:28:28 +0000] [27201] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:28:28 +0000] [27201] [INFO] Listening at: http://127.0.0.1:8000 (27201)
[2019-01-02 08:28:28 +0000] [27201] [INFO] Using worker: sync
[2019-01-02 08:28:28 +0000] [27205] [INFO] Booting worker with pid: 27205
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:30:06 +0000] [27201] [INFO] Handling signal: term
[2019-01-02 08:30:06 +0000] [27205] [INFO] Worker exiting (pid: 27205)
[2019-01-02 08:30:06 +0000] [27201] [INFO] Shutting down: Master
[2019-01-02 08:30:06 +0000] [27211] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:30:06 +0000] [27211] [INFO] Listening at: http://127.0.0.1:8000 (27211)
[2019-01-02 08:30:06 +0000] [27211] [INFO] Using worker: sync
[2019-01-02 08:30:06 +0000] [27215] [INFO] Booting worker with pid: 27215
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:33:57 +0000] [27211] [INFO] Handling signal: term
[2019-01-02 08:33:57 +0000] [27215] [INFO] Worker exiting (pid: 27215)
[2019-01-02 08:33:57 +0000] [27211] [INFO] Shutting down: Master
[2019-01-02 08:33:57 +0000] [27222] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:33:57 +0000] [27222] [INFO] Listening at: http://127.0.0.1:8000 (27222)
[2019-01-02 08:33:57 +0000] [27222] [INFO] Using worker: sync
[2019-01-02 08:33:57 +0000] [27226] [INFO] Booting worker with pid: 27226
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:34:39 +0000] [27222] [INFO] Handling signal: term
[2019-01-02 08:34:39 +0000] [27226] [INFO] Worker exiting (pid: 27226)
[2019-01-02 08:34:39 +0000] [27222] [INFO] Shutting down: Master
[2019-01-02 08:34:39 +0000] [27231] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:34:39 +0000] [27231] [INFO] Listening at: http://127.0.0.1:8000 (27231)
[2019-01-02 08:34:39 +0000] [27231] [INFO] Using worker: sync
[2019-01-02 08:34:39 +0000] [27235] [INFO] Booting worker with pid: 27235
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:37:22 +0000] [27231] [INFO] Handling signal: term
[2019-01-02 08:37:22 +0000] [27235] [INFO] Worker exiting (pid: 27235)
[2019-01-02 08:37:22 +0000] [27231] [INFO] Shutting down: Master
[2019-01-02 08:37:22 +0000] [27240] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:37:22 +0000] [27240] [INFO] Listening at: http://127.0.0.1:8000 (27240)
[2019-01-02 08:37:22 +0000] [27240] [INFO] Using worker: sync
[2019-01-02 08:37:22 +0000] [27244] [INFO] Booting worker with pid: 27244
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 08:46:22 +0000] [27240] [INFO] Handling signal: term
[2019-01-02 08:46:22 +0000] [27244] [INFO] Worker exiting (pid: 27244)
[2019-01-02 08:46:22 +0000] [27240] [INFO] Shutting down: Master
[2019-01-02 08:46:23 +0000] [27249] [INFO] Starting gunicorn 19.9.0
[2019-01-02 08:46:23 +0000] [27249] [INFO] Listening at: http://127.0.0.1:8000 (27249)
[2019-01-02 08:46:23 +0000] [27249] [INFO] Using worker: sync
[2019-01-02 08:46:23 +0000] [27253] [INFO] Booting worker with pid: 27253
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 09:05:39 +0000] [27253] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 09:05:42 +0000] [27249] [INFO] Handling signal: term
[2019-01-02 09:05:42 +0000] [27253] [INFO] Worker exiting (pid: 27253)
[2019-01-02 09:05:42 +0000] [27249] [INFO] Shutting down: Master
[2019-01-02 09:05:43 +0000] [27264] [INFO] Starting gunicorn 19.9.0
[2019-01-02 09:05:43 +0000] [27264] [INFO] Listening at: http://127.0.0.1:8000 (27264)
[2019-01-02 09:05:43 +0000] [27264] [INFO] Using worker: sync
[2019-01-02 09:05:43 +0000] [27268] [INFO] Booting worker with pid: 27268
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 09:07:24 +0000] [27264] [INFO] Handling signal: term
[2019-01-02 09:07:24 +0000] [27268] [INFO] Worker exiting (pid: 27268)
[2019-01-02 09:07:24 +0000] [27264] [INFO] Shutting down: Master
[2019-01-02 09:07:24 +0000] [27273] [INFO] Starting gunicorn 19.9.0
[2019-01-02 09:07:24 +0000] [27273] [INFO] Listening at: http://127.0.0.1:8000 (27273)
[2019-01-02 09:07:24 +0000] [27273] [INFO] Using worker: sync
[2019-01-02 09:07:24 +0000] [27277] [INFO] Booting worker with pid: 27277
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:24:54 +0000] [27277] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 19:24:58 +0000] [27277] [INFO] Worker exiting (pid: 27277)
[2019-01-02 19:24:58 +0000] [28170] [INFO] Booting worker with pid: 28170
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:25:05 +0000] [27273] [INFO] Handling signal: term
[2019-01-02 19:25:05 +0000] [28170] [INFO] Worker exiting (pid: 28170)
[2019-01-02 19:25:05 +0000] [27273] [INFO] Shutting down: Master
[2019-01-02 19:25:05 +0000] [28175] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:25:05 +0000] [28175] [INFO] Listening at: http://127.0.0.1:8000 (28175)
[2019-01-02 19:25:05 +0000] [28175] [INFO] Using worker: sync
[2019-01-02 19:25:05 +0000] [28179] [INFO] Booting worker with pid: 28179
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:30:09 +0000] [28179] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 19:30:20 +0000] [28179] [INFO] Worker exiting (pid: 28179)
[2019-01-02 19:30:20 +0000] [28226] [INFO] Booting worker with pid: 28226
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:30:33 +0000] [28226] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 19:30:35 +0000] [28226] [INFO] Worker exiting (pid: 28226)
[2019-01-02 19:30:36 +0000] [28229] [INFO] Booting worker with pid: 28229
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:31:15 +0000] [28229] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 19:31:21 +0000] [28229] [INFO] Worker exiting (pid: 28229)
[2019-01-02 19:31:21 +0000] [28232] [INFO] Booting worker with pid: 28232
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:32:04 +0000] [28232] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 19:32:05 +0000] [28232] [INFO] Worker exiting (pid: 28232)
[2019-01-02 19:32:05 +0000] [28235] [INFO] Booting worker with pid: 28235
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:36:36 +0000] [28175] [INFO] Handling signal: term
[2019-01-02 19:36:36 +0000] [28235] [INFO] Worker exiting (pid: 28235)
[2019-01-02 19:36:36 +0000] [28175] [INFO] Shutting down: Master
[2019-01-02 19:36:36 +0000] [28261] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:36:36 +0000] [28261] [INFO] Listening at: http://127.0.0.1:8000 (28261)
[2019-01-02 19:36:36 +0000] [28261] [INFO] Using worker: sync
[2019-01-02 19:36:36 +0000] [28265] [INFO] Booting worker with pid: 28265
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:37:03 +0000] [28261] [INFO] Handling signal: term
[2019-01-02 19:37:03 +0000] [28265] [INFO] Worker exiting (pid: 28265)
[2019-01-02 19:37:03 +0000] [28261] [INFO] Shutting down: Master
[2019-01-02 19:37:03 +0000] [28282] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:37:03 +0000] [28282] [INFO] Listening at: http://127.0.0.1:8000 (28282)
[2019-01-02 19:37:03 +0000] [28282] [INFO] Using worker: sync
[2019-01-02 19:37:03 +0000] [28286] [INFO] Booting worker with pid: 28286
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:37:36 +0000] [28282] [INFO] Handling signal: term
[2019-01-02 19:37:36 +0000] [28286] [INFO] Worker exiting (pid: 28286)
[2019-01-02 19:37:36 +0000] [28282] [INFO] Shutting down: Master
[2019-01-02 19:37:36 +0000] [28299] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:37:36 +0000] [28299] [INFO] Listening at: http://127.0.0.1:8000 (28299)
[2019-01-02 19:37:36 +0000] [28299] [INFO] Using worker: sync
[2019-01-02 19:37:36 +0000] [28303] [INFO] Booting worker with pid: 28303
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:42:53 +0000] [28299] [INFO] Handling signal: term
[2019-01-02 19:42:53 +0000] [28303] [INFO] Worker exiting (pid: 28303)
[2019-01-02 19:42:53 +0000] [28299] [INFO] Shutting down: Master
[2019-01-02 19:42:53 +0000] [28315] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:42:53 +0000] [28315] [INFO] Listening at: http://127.0.0.1:8000 (28315)
[2019-01-02 19:42:53 +0000] [28315] [INFO] Using worker: sync
[2019-01-02 19:42:53 +0000] [28319] [INFO] Booting worker with pid: 28319
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:43:27 +0000] [28315] [INFO] Handling signal: term
[2019-01-02 19:43:27 +0000] [28319] [INFO] Worker exiting (pid: 28319)
[2019-01-02 19:43:27 +0000] [28315] [INFO] Shutting down: Master
[2019-01-02 19:43:28 +0000] [28324] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:43:28 +0000] [28324] [INFO] Listening at: http://127.0.0.1:8000 (28324)
[2019-01-02 19:43:28 +0000] [28324] [INFO] Using worker: sync
[2019-01-02 19:43:28 +0000] [28328] [INFO] Booting worker with pid: 28328
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:44:55 +0000] [28324] [INFO] Handling signal: term
[2019-01-02 19:44:55 +0000] [28328] [INFO] Worker exiting (pid: 28328)
[2019-01-02 19:44:55 +0000] [28324] [INFO] Shutting down: Master
[2019-01-02 19:44:55 +0000] [28350] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:44:55 +0000] [28350] [INFO] Listening at: http://127.0.0.1:8000 (28350)
[2019-01-02 19:44:55 +0000] [28350] [INFO] Using worker: sync
[2019-01-02 19:44:55 +0000] [28354] [INFO] Booting worker with pid: 28354
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:45:22 +0000] [28350] [INFO] Handling signal: term
[2019-01-02 19:45:22 +0000] [28354] [INFO] Worker exiting (pid: 28354)
[2019-01-02 19:45:22 +0000] [28350] [INFO] Shutting down: Master
[2019-01-02 19:45:22 +0000] [28359] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:45:22 +0000] [28359] [INFO] Listening at: http://127.0.0.1:8000 (28359)
[2019-01-02 19:45:22 +0000] [28359] [INFO] Using worker: sync
[2019-01-02 19:45:22 +0000] [28363] [INFO] Booting worker with pid: 28363
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:46:30 +0000] [28359] [INFO] Handling signal: term
[2019-01-02 19:46:30 +0000] [28363] [INFO] Worker exiting (pid: 28363)
[2019-01-02 19:46:30 +0000] [28359] [INFO] Shutting down: Master
[2019-01-02 19:46:30 +0000] [28368] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:46:30 +0000] [28368] [INFO] Listening at: http://127.0.0.1:8000 (28368)
[2019-01-02 19:46:30 +0000] [28368] [INFO] Using worker: sync
[2019-01-02 19:46:30 +0000] [28372] [INFO] Booting worker with pid: 28372
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:49:39 +0000] [28368] [INFO] Handling signal: term
[2019-01-02 19:49:39 +0000] [28372] [INFO] Worker exiting (pid: 28372)
[2019-01-02 19:49:39 +0000] [28368] [INFO] Shutting down: Master
[2019-01-02 19:49:39 +0000] [28378] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:49:39 +0000] [28378] [INFO] Listening at: http://127.0.0.1:8000 (28378)
[2019-01-02 19:49:39 +0000] [28378] [INFO] Using worker: sync
[2019-01-02 19:49:39 +0000] [28382] [INFO] Booting worker with pid: 28382
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 19:53:15 +0000] [28378] [INFO] Handling signal: term
[2019-01-02 19:53:15 +0000] [28382] [INFO] Worker exiting (pid: 28382)
[2019-01-02 19:53:15 +0000] [28378] [INFO] Shutting down: Master
[2019-01-02 19:53:15 +0000] [28388] [INFO] Starting gunicorn 19.9.0
[2019-01-02 19:53:15 +0000] [28388] [INFO] Listening at: http://127.0.0.1:8000 (28388)
[2019-01-02 19:53:15 +0000] [28388] [INFO] Using worker: sync
[2019-01-02 19:53:15 +0000] [28392] [INFO] Booting worker with pid: 28392
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 20:27:09 +0000] [28388] [INFO] Handling signal: term
[2019-01-02 20:27:09 +0000] [28392] [INFO] Worker exiting (pid: 28392)
[2019-01-02 20:27:09 +0000] [28388] [INFO] Shutting down: Master
[2019-01-02 20:27:09 +0000] [28493] [INFO] Starting gunicorn 19.9.0
[2019-01-02 20:27:09 +0000] [28493] [INFO] Listening at: http://127.0.0.1:8000 (28493)
[2019-01-02 20:27:09 +0000] [28493] [INFO] Using worker: sync
[2019-01-02 20:27:09 +0000] [28497] [INFO] Booting worker with pid: 28497
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:38:05 +0000] [28497] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:38:17 +0000] [28497] [INFO] Worker exiting (pid: 28497)
[2019-01-02 22:38:17 +0000] [28788] [INFO] Booting worker with pid: 28788
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:38:52 +0000] [28788] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:38:57 +0000] [28788] [INFO] Worker exiting (pid: 28788)
[2019-01-02 22:38:57 +0000] [28791] [INFO] Booting worker with pid: 28791
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:39:19 +0000] [28791] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:39:20 +0000] [28791] [INFO] Worker exiting (pid: 28791)
[2019-01-02 22:39:20 +0000] [28794] [INFO] Booting worker with pid: 28794
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:39:28 +0000] [28794] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:39:29 +0000] [28794] [INFO] Worker exiting (pid: 28794)
[2019-01-02 22:39:29 +0000] [28797] [INFO] Booting worker with pid: 28797
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:39:56 +0000] [28797] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:39:56 +0000] [28797] [INFO] Worker exiting (pid: 28797)
[2019-01-02 22:39:56 +0000] [28800] [INFO] Booting worker with pid: 28800
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:40:19 +0000] [28800] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:40:19 +0000] [28800] [INFO] Worker exiting (pid: 28800)
[2019-01-02 22:40:19 +0000] [28803] [INFO] Booting worker with pid: 28803
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:40:43 +0000] [28803] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:40:50 +0000] [28803] [INFO] Worker exiting (pid: 28803)
[2019-01-02 22:40:50 +0000] [28806] [INFO] Booting worker with pid: 28806
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:42:27 +0000] [28806] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:42:30 +0000] [28806] [INFO] Worker exiting (pid: 28806)
[2019-01-02 22:42:30 +0000] [28809] [INFO] Booting worker with pid: 28809
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:43:04 +0000] [28809] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:43:05 +0000] [28809] [INFO] Worker exiting (pid: 28809)
[2019-01-02 22:43:05 +0000] [28815] [INFO] Booting worker with pid: 28815
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-02 22:47:15 +0000] [28815] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-02 22:47:16 +0000] [28815] [INFO] Worker exiting (pid: 28815)
[2019-01-02 22:47:16 +0000] [28818] [INFO] Booting worker with pid: 28818
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-03 21:23:56 +0000] [28493] [INFO] Handling signal: hup
[2019-01-03 21:23:56 +0000] [28493] [INFO] Hang up: Master
[2019-01-03 21:23:56 +0000] [31883] [INFO] Booting worker with pid: 31883
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 01:58:59 +0000] [31883] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 01:59:02 +0000] [31883] [INFO] Worker exiting (pid: 31883)
[2019-01-04 01:59:02 +0000] [11940] [INFO] Booting worker with pid: 11940
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 01:59:13 +0000] [11940] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 01:59:14 +0000] [11940] [INFO] Worker exiting (pid: 11940)
[2019-01-04 01:59:14 +0000] [11943] [INFO] Booting worker with pid: 11943
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:02:11 +0000] [11943] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:02:11 +0000] [11943] [INFO] Worker exiting (pid: 11943)
[2019-01-04 02:02:11 +0000] [11946] [INFO] Booting worker with pid: 11946
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:02:21 +0000] [11946] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:02:23 +0000] [11946] [INFO] Worker exiting (pid: 11946)
[2019-01-04 02:02:23 +0000] [11949] [INFO] Booting worker with pid: 11949
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:02:37 +0000] [11949] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:02:38 +0000] [11949] [INFO] Worker exiting (pid: 11949)
[2019-01-04 02:02:38 +0000] [11952] [INFO] Booting worker with pid: 11952
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:03:13 +0000] [11952] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:03:14 +0000] [11952] [INFO] Worker exiting (pid: 11952)
[2019-01-04 02:03:14 +0000] [11955] [INFO] Booting worker with pid: 11955
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:04:12 +0000] [11955] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:04:12 +0000] [11955] [INFO] Worker exiting (pid: 11955)
[2019-01-04 02:04:12 +0000] [11960] [INFO] Booting worker with pid: 11960
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:05:08 +0000] [11960] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:05:09 +0000] [11960] [INFO] Worker exiting (pid: 11960)
[2019-01-04 02:05:10 +0000] [11963] [INFO] Booting worker with pid: 11963
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:05:27 +0000] [11963] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:05:40 +0000] [11963] [INFO] Worker exiting (pid: 11963)
[2019-01-04 02:05:40 +0000] [11966] [INFO] Booting worker with pid: 11966
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:07:26 +0000] [11966] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:07:27 +0000] [11966] [INFO] Worker exiting (pid: 11966)
[2019-01-04 02:07:27 +0000] [11969] [INFO] Booting worker with pid: 11969
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:08:57 +0000] [11969] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:08:58 +0000] [11969] [INFO] Worker exiting (pid: 11969)
[2019-01-04 02:08:58 +0000] [11972] [INFO] Booting worker with pid: 11972
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:09:10 +0000] [11972] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:09:13 +0000] [11972] [INFO] Worker exiting (pid: 11972)
[2019-01-04 02:09:13 +0000] [11976] [INFO] Booting worker with pid: 11976
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:09:27 +0000] [11976] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:09:28 +0000] [11976] [INFO] Worker exiting (pid: 11976)
[2019-01-04 02:09:28 +0000] [11979] [INFO] Booting worker with pid: 11979
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:09:38 +0000] [11979] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:09:39 +0000] [11979] [INFO] Worker exiting (pid: 11979)
[2019-01-04 02:09:39 +0000] [11982] [INFO] Booting worker with pid: 11982
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:11:38 +0000] [11982] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:11:39 +0000] [11982] [INFO] Worker exiting (pid: 11982)
[2019-01-04 02:11:39 +0000] [11985] [INFO] Booting worker with pid: 11985
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:12:36 +0000] [11985] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:12:37 +0000] [11985] [INFO] Worker exiting (pid: 11985)
[2019-01-04 02:12:37 +0000] [11989] [INFO] Booting worker with pid: 11989
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:13:19 +0000] [11989] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:13:19 +0000] [11989] [INFO] Worker exiting (pid: 11989)
[2019-01-04 02:13:20 +0000] [11992] [INFO] Booting worker with pid: 11992
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:19:05 +0000] [11992] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:19:05 +0000] [11992] [INFO] Worker exiting (pid: 11992)
[2019-01-04 02:19:05 +0000] [12002] [INFO] Booting worker with pid: 12002
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:19:19 +0000] [12002] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:19:21 +0000] [12002] [INFO] Worker exiting (pid: 12002)
[2019-01-04 02:19:21 +0000] [12005] [INFO] Booting worker with pid: 12005
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:19:28 +0000] [12005] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:19:29 +0000] [12005] [INFO] Worker exiting (pid: 12005)
[2019-01-04 02:19:29 +0000] [12008] [INFO] Booting worker with pid: 12008
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:23:08 +0000] [12008] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:23:14 +0000] [12008] [INFO] Worker exiting (pid: 12008)
[2019-01-04 02:23:14 +0000] [12012] [INFO] Booting worker with pid: 12012
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:27:05 +0000] [12012] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:27:07 +0000] [12012] [INFO] Worker exiting (pid: 12012)
[2019-01-04 02:27:07 +0000] [12016] [INFO] Booting worker with pid: 12016
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:29:24 +0000] [12016] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:29:37 +0000] [12016] [INFO] Worker exiting (pid: 12016)
[2019-01-04 02:29:37 +0000] [12020] [INFO] Booting worker with pid: 12020
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 02:59:10 +0000] [12020] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-04 02:59:24 +0000] [12020] [INFO] Worker exiting (pid: 12020)
[2019-01-04 02:59:24 +0000] [12036] [INFO] Booting worker with pid: 12036
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-04 20:01:18 +0000] [12036] [INFO] Worker exiting (pid: 12036)
[2019-01-04 20:01:18 +0000] [28493] [INFO] Handling signal: term
./gun.sh: 2: ./gun.sh: gunicorn: not found
[2019-01-04 20:01:18 +0000] [28493] [INFO] Shutting down: Master
./gun.sh: 2: ./gun.sh: ost:8000: not found
pkill: killing pid 13299 failed: Operation not permitted
pkill: killing pid 18547 failed: Operation not permitted
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-08 17:07:19 +0000] [20515] [INFO] Starting gunicorn 19.9.0
[2019-01-08 17:07:19 +0000] [20515] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:07:19 +0000] [20515] [ERROR] Retrying in 1 second.
[2019-01-08 17:07:20 +0000] [20515] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:07:20 +0000] [20515] [ERROR] Retrying in 1 second.
[2019-01-08 17:07:21 +0000] [20515] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:07:21 +0000] [20515] [ERROR] Retrying in 1 second.
[2019-01-08 17:07:22 +0000] [20515] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:07:22 +0000] [20515] [ERROR] Retrying in 1 second.
[2019-01-08 17:07:23 +0000] [20515] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:07:23 +0000] [20515] [ERROR] Retrying in 1 second.
[2019-01-08 17:07:24 +0000] [20515] [ERROR] Can't connect to ('localhost', 8000)
pkill: killing pid 13299 failed: Operation not permitted
pkill: killing pid 18547 failed: Operation not permitted
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-08 17:08:23 +0000] [20574] [INFO] Starting gunicorn 19.9.0
[2019-01-08 17:08:23 +0000] [20574] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:08:23 +0000] [20574] [ERROR] Retrying in 1 second.
[2019-01-08 17:08:24 +0000] [20574] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:08:24 +0000] [20574] [ERROR] Retrying in 1 second.
[2019-01-08 17:08:25 +0000] [20574] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:08:25 +0000] [20574] [ERROR] Retrying in 1 second.
[2019-01-08 17:08:26 +0000] [20574] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:08:26 +0000] [20574] [ERROR] Retrying in 1 second.
[2019-01-08 17:08:27 +0000] [20574] [ERROR] Connection in use: ('localhost', 8000)
[2019-01-08 17:08:27 +0000] [20574] [ERROR] Retrying in 1 second.
[2019-01-08 17:08:28 +0000] [20574] [ERROR] Can't connect to ('localhost', 8000)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-08 17:19:05 +0000] [20663] [INFO] Starting gunicorn 19.9.0
[2019-01-08 17:19:05 +0000] [20663] [INFO] Listening at: http://127.0.0.1:8000 (20663)
[2019-01-08 17:19:05 +0000] [20663] [INFO] Using worker: sync
[2019-01-08 17:19:05 +0000] [20667] [INFO] Booting worker with pid: 20667
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-08 22:31:32 +0000] [20663] [INFO] Handling signal: term
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-08 22:31:32 +0000] [20667] [INFO] Worker exiting (pid: 20667)
[2019-01-08 22:31:32 +0000] [20663] [INFO] Shutting down: Master
[2019-01-08 22:31:32 +0000] [21457] [INFO] Starting gunicorn 19.9.0
[2019-01-08 22:31:32 +0000] [21457] [INFO] Listening at: http://127.0.0.1:8000 (21457)
[2019-01-08 22:31:32 +0000] [21457] [INFO] Using worker: sync
[2019-01-08 22:31:32 +0000] [21461] [INFO] Booting worker with pid: 21461
[2019-01-08 22:31:32 +0000] [21461] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-08 22:31:32 +0000] [21461] [INFO] Worker exiting (pid: 21461)
[2019-01-08 22:31:32 +0000] [21457] [INFO] Shutting down: Master
[2019-01-08 22:31:32 +0000] [21457] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-08 22:32:03 +0000] [21485] [INFO] Starting gunicorn 19.9.0
[2019-01-08 22:32:03 +0000] [21485] [INFO] Listening at: http://127.0.0.1:8000 (21485)
[2019-01-08 22:32:03 +0000] [21485] [INFO] Using worker: sync
[2019-01-08 22:32:03 +0000] [21489] [INFO] Booting worker with pid: 21489
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-08 22:50:52 +0000] [21485] [INFO] Handling signal: term
[2019-01-08 22:50:52 +0000] [21489] [INFO] Worker exiting (pid: 21489)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-08 22:50:52 +0000] [21485] [INFO] Shutting down: Master
[2019-01-08 22:50:52 +0000] [21503] [INFO] Starting gunicorn 19.9.0
[2019-01-08 22:50:52 +0000] [21503] [INFO] Listening at: http://127.0.0.1:8000 (21503)
[2019-01-08 22:50:52 +0000] [21503] [INFO] Using worker: sync
[2019-01-08 22:50:52 +0000] [21507] [INFO] Booting worker with pid: 21507
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 19:11:26 +0000] [21503] [INFO] Handling signal: term
[2019-01-09 19:11:26 +0000] [21507] [INFO] Worker exiting (pid: 21507)
[2019-01-09 19:11:26 +0000] [21503] [INFO] Shutting down: Master
[2019-01-09 19:11:26 +0000] [25036] [INFO] Starting gunicorn 19.9.0
[2019-01-09 19:11:26 +0000] [25036] [INFO] Listening at: http://127.0.0.1:8000 (25036)
[2019-01-09 19:11:26 +0000] [25036] [INFO] Using worker: sync
[2019-01-09 19:11:26 +0000] [25040] [INFO] Booting worker with pid: 25040
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 20:09:35 +0000] [25040] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-09 20:09:38 +0000] [25040] [INFO] Worker exiting (pid: 25040)
[2019-01-09 20:09:38 +0000] [25142] [INFO] Booting worker with pid: 25142
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 20:09:55 +0000] [25142] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-09 20:09:58 +0000] [25142] [INFO] Worker exiting (pid: 25142)
[2019-01-09 20:09:58 +0000] [25145] [INFO] Booting worker with pid: 25145
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 22:26:07 +0000] [25036] [INFO] Handling signal: term
[2019-01-09 22:26:07 +0000] [25145] [INFO] Worker exiting (pid: 25145)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 22:26:07 +0000] [25036] [INFO] Shutting down: Master
[2019-01-09 22:26:07 +0000] [25506] [INFO] Starting gunicorn 19.9.0
[2019-01-09 22:26:07 +0000] [25506] [INFO] Listening at: http://127.0.0.1:8000 (25506)
[2019-01-09 22:26:07 +0000] [25506] [INFO] Using worker: sync
[2019-01-09 22:26:07 +0000] [25510] [INFO] Booting worker with pid: 25510
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 22:28:10 +0000] [25506] [INFO] Handling signal: term
[2019-01-09 22:28:10 +0000] [25510] [INFO] Worker exiting (pid: 25510)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 22:28:10 +0000] [25506] [INFO] Shutting down: Master
[2019-01-09 22:28:10 +0000] [25548] [INFO] Starting gunicorn 19.9.0
[2019-01-09 22:28:10 +0000] [25548] [INFO] Listening at: http://127.0.0.1:8000 (25548)
[2019-01-09 22:28:10 +0000] [25548] [INFO] Using worker: sync
[2019-01-09 22:28:10 +0000] [25552] [INFO] Booting worker with pid: 25552
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 22:28:57 +0000] [25548] [INFO] Handling signal: term
[2019-01-09 22:28:57 +0000] [25552] [INFO] Worker exiting (pid: 25552)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 22:28:57 +0000] [25548] [INFO] Shutting down: Master
[2019-01-09 22:28:57 +0000] [25560] [INFO] Starting gunicorn 19.9.0
[2019-01-09 22:28:57 +0000] [25560] [INFO] Listening at: http://127.0.0.1:8000 (25560)
[2019-01-09 22:28:57 +0000] [25560] [INFO] Using worker: sync
[2019-01-09 22:28:57 +0000] [25564] [INFO] Booting worker with pid: 25564
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 22:33:52 +0000] [25560] [INFO] Handling signal: term
[2019-01-09 22:33:52 +0000] [25564] [INFO] Worker exiting (pid: 25564)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 22:33:52 +0000] [25560] [INFO] Shutting down: Master
[2019-01-09 22:33:52 +0000] [25569] [INFO] Starting gunicorn 19.9.0
[2019-01-09 22:33:52 +0000] [25569] [INFO] Listening at: http://127.0.0.1:8000 (25569)
[2019-01-09 22:33:52 +0000] [25569] [INFO] Using worker: sync
[2019-01-09 22:33:52 +0000] [25573] [INFO] Booting worker with pid: 25573
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 22:34:24 +0000] [25573] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-09 22:34:25 +0000] [25573] [INFO] Worker exiting (pid: 25573)
[2019-01-09 22:34:25 +0000] [25576] [INFO] Booting worker with pid: 25576
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:17:04 +0000] [25576] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-09 23:17:05 +0000] [25576] [INFO] Worker exiting (pid: 25576)
[2019-01-09 23:17:05 +0000] [25603] [INFO] Booting worker with pid: 25603
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:17:17 +0000] [25603] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-09 23:17:28 +0000] [25603] [INFO] Worker exiting (pid: 25603)
[2019-01-09 23:17:28 +0000] [25607] [INFO] Booting worker with pid: 25607
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:21:58 +0000] [25569] [INFO] Handling signal: term
[2019-01-09 23:21:58 +0000] [25607] [INFO] Worker exiting (pid: 25607)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:21:58 +0000] [25569] [INFO] Shutting down: Master
[2019-01-09 23:21:58 +0000] [25662] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:21:58 +0000] [25662] [INFO] Listening at: http://127.0.0.1:8000 (25662)
[2019-01-09 23:21:58 +0000] [25662] [INFO] Using worker: sync
[2019-01-09 23:21:58 +0000] [25666] [INFO] Booting worker with pid: 25666
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:24:33 +0000] [25662] [INFO] Handling signal: term
[2019-01-09 23:24:33 +0000] [25666] [INFO] Worker exiting (pid: 25666)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:24:33 +0000] [25662] [INFO] Shutting down: Master
[2019-01-09 23:24:33 +0000] [25671] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:24:33 +0000] [25671] [INFO] Listening at: http://127.0.0.1:8000 (25671)
[2019-01-09 23:24:33 +0000] [25671] [INFO] Using worker: sync
[2019-01-09 23:24:33 +0000] [25675] [INFO] Booting worker with pid: 25675
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:27:18 +0000] [25671] [INFO] Handling signal: term
[2019-01-09 23:27:18 +0000] [25675] [INFO] Worker exiting (pid: 25675)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:27:18 +0000] [25671] [INFO] Shutting down: Master
[2019-01-09 23:27:19 +0000] [25683] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:27:19 +0000] [25683] [INFO] Listening at: http://127.0.0.1:8000 (25683)
[2019-01-09 23:27:19 +0000] [25683] [INFO] Using worker: sync
[2019-01-09 23:27:19 +0000] [25687] [INFO] Booting worker with pid: 25687
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:33:46 +0000] [25683] [INFO] Handling signal: term
[2019-01-09 23:33:46 +0000] [25687] [INFO] Worker exiting (pid: 25687)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:33:46 +0000] [25683] [INFO] Shutting down: Master
[2019-01-09 23:33:46 +0000] [25693] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:33:46 +0000] [25693] [INFO] Listening at: http://127.0.0.1:8000 (25693)
[2019-01-09 23:33:46 +0000] [25693] [INFO] Using worker: sync
[2019-01-09 23:33:46 +0000] [25697] [INFO] Booting worker with pid: 25697
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:37:18 +0000] [25693] [INFO] Handling signal: term
[2019-01-09 23:37:18 +0000] [25697] [INFO] Worker exiting (pid: 25697)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:37:18 +0000] [25693] [INFO] Shutting down: Master
[2019-01-09 23:37:18 +0000] [25702] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:37:18 +0000] [25702] [INFO] Listening at: http://127.0.0.1:8000 (25702)
[2019-01-09 23:37:18 +0000] [25702] [INFO] Using worker: sync
[2019-01-09 23:37:18 +0000] [25706] [INFO] Booting worker with pid: 25706
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:41:29 +0000] [25702] [INFO] Handling signal: term
[2019-01-09 23:41:29 +0000] [25706] [INFO] Worker exiting (pid: 25706)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:41:29 +0000] [25702] [INFO] Shutting down: Master
[2019-01-09 23:41:29 +0000] [25711] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:41:29 +0000] [25711] [INFO] Listening at: http://127.0.0.1:8000 (25711)
[2019-01-09 23:41:29 +0000] [25711] [INFO] Using worker: sync
[2019-01-09 23:41:29 +0000] [25715] [INFO] Booting worker with pid: 25715
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:42:27 +0000] [25711] [INFO] Handling signal: term
[2019-01-09 23:42:27 +0000] [25715] [INFO] Worker exiting (pid: 25715)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:42:27 +0000] [25711] [INFO] Shutting down: Master
[2019-01-09 23:42:27 +0000] [25720] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:42:27 +0000] [25720] [INFO] Listening at: http://127.0.0.1:8000 (25720)
[2019-01-09 23:42:27 +0000] [25720] [INFO] Using worker: sync
[2019-01-09 23:42:27 +0000] [25724] [INFO] Booting worker with pid: 25724
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:45:32 +0000] [25720] [INFO] Handling signal: term
[2019-01-09 23:45:32 +0000] [25724] [INFO] Worker exiting (pid: 25724)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:45:32 +0000] [25720] [INFO] Shutting down: Master
[2019-01-09 23:45:32 +0000] [25729] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:45:32 +0000] [25729] [INFO] Listening at: http://127.0.0.1:8000 (25729)
[2019-01-09 23:45:32 +0000] [25729] [INFO] Using worker: sync
[2019-01-09 23:45:32 +0000] [25733] [INFO] Booting worker with pid: 25733
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-09 23:57:35 +0000] [25729] [INFO] Handling signal: term
[2019-01-09 23:57:35 +0000] [25733] [INFO] Worker exiting (pid: 25733)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-09 23:57:35 +0000] [25729] [INFO] Shutting down: Master
[2019-01-09 23:57:35 +0000] [25741] [INFO] Starting gunicorn 19.9.0
[2019-01-09 23:57:35 +0000] [25741] [INFO] Listening at: http://127.0.0.1:8000 (25741)
[2019-01-09 23:57:35 +0000] [25741] [INFO] Using worker: sync
[2019-01-09 23:57:35 +0000] [25745] [INFO] Booting worker with pid: 25745
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:12:42 +0000] [25741] [INFO] Handling signal: term
[2019-01-10 00:12:42 +0000] [25745] [INFO] Worker exiting (pid: 25745)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:12:42 +0000] [25741] [INFO] Shutting down: Master
[2019-01-10 00:12:42 +0000] [25751] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:12:42 +0000] [25751] [INFO] Listening at: http://127.0.0.1:8000 (25751)
[2019-01-10 00:12:42 +0000] [25751] [INFO] Using worker: sync
[2019-01-10 00:12:42 +0000] [25755] [INFO] Booting worker with pid: 25755
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:14:24 +0000] [25751] [INFO] Handling signal: term
[2019-01-10 00:14:24 +0000] [25755] [INFO] Worker exiting (pid: 25755)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:14:24 +0000] [25751] [INFO] Shutting down: Master
[2019-01-10 00:14:24 +0000] [25762] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:14:24 +0000] [25762] [INFO] Listening at: http://127.0.0.1:8000 (25762)
[2019-01-10 00:14:24 +0000] [25762] [INFO] Using worker: sync
[2019-01-10 00:14:24 +0000] [25766] [INFO] Booting worker with pid: 25766
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:15:23 +0000] [25762] [INFO] Handling signal: term
[2019-01-10 00:15:23 +0000] [25766] [INFO] Worker exiting (pid: 25766)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:15:23 +0000] [25762] [INFO] Shutting down: Master
[2019-01-10 00:15:23 +0000] [25771] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:15:23 +0000] [25771] [INFO] Listening at: http://127.0.0.1:8000 (25771)
[2019-01-10 00:15:23 +0000] [25771] [INFO] Using worker: sync
[2019-01-10 00:15:23 +0000] [25775] [INFO] Booting worker with pid: 25775
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:16:19 +0000] [25771] [INFO] Handling signal: term
[2019-01-10 00:16:19 +0000] [25775] [INFO] Worker exiting (pid: 25775)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:16:19 +0000] [25771] [INFO] Shutting down: Master
[2019-01-10 00:16:19 +0000] [25780] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:16:19 +0000] [25780] [INFO] Listening at: http://127.0.0.1:8000 (25780)
[2019-01-10 00:16:19 +0000] [25780] [INFO] Using worker: sync
[2019-01-10 00:16:19 +0000] [25784] [INFO] Booting worker with pid: 25784
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:16:54 +0000] [25780] [INFO] Handling signal: term
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:16:54 +0000] [25784] [INFO] Worker exiting (pid: 25784)
[2019-01-10 00:16:54 +0000] [25780] [INFO] Shutting down: Master
[2019-01-10 00:16:54 +0000] [25789] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:16:54 +0000] [25789] [INFO] Listening at: http://127.0.0.1:8000 (25789)
[2019-01-10 00:16:54 +0000] [25789] [INFO] Using worker: sync
[2019-01-10 00:16:54 +0000] [25793] [INFO] Booting worker with pid: 25793
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:17:12 +0000] [25789] [INFO] Handling signal: term
[2019-01-10 00:17:12 +0000] [25793] [INFO] Worker exiting (pid: 25793)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:17:12 +0000] [25789] [INFO] Shutting down: Master
[2019-01-10 00:17:12 +0000] [25801] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:17:12 +0000] [25801] [INFO] Listening at: http://127.0.0.1:8000 (25801)
[2019-01-10 00:17:12 +0000] [25801] [INFO] Using worker: sync
[2019-01-10 00:17:12 +0000] [25805] [INFO] Booting worker with pid: 25805
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:27:21 +0000] [25801] [INFO] Handling signal: term
[2019-01-10 00:27:21 +0000] [25805] [INFO] Worker exiting (pid: 25805)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:27:21 +0000] [25801] [INFO] Shutting down: Master
[2019-01-10 00:27:21 +0000] [26037] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:27:21 +0000] [26037] [INFO] Listening at: http://127.0.0.1:8000 (26037)
[2019-01-10 00:27:21 +0000] [26037] [INFO] Using worker: sync
[2019-01-10 00:27:21 +0000] [26041] [INFO] Booting worker with pid: 26041
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:28:24 +0000] [26037] [INFO] Handling signal: term
[2019-01-10 00:28:24 +0000] [26041] [INFO] Worker exiting (pid: 26041)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:28:24 +0000] [26037] [INFO] Shutting down: Master
[2019-01-10 00:28:24 +0000] [26046] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:28:24 +0000] [26046] [INFO] Listening at: http://127.0.0.1:8000 (26046)
[2019-01-10 00:28:24 +0000] [26046] [INFO] Using worker: sync
[2019-01-10 00:28:24 +0000] [26050] [INFO] Booting worker with pid: 26050
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:29:03 +0000] [26046] [INFO] Handling signal: term
[2019-01-10 00:29:03 +0000] [26050] [INFO] Worker exiting (pid: 26050)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:29:03 +0000] [26046] [INFO] Shutting down: Master
[2019-01-10 00:29:03 +0000] [26055] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:29:03 +0000] [26055] [INFO] Listening at: http://127.0.0.1:8000 (26055)
[2019-01-10 00:29:03 +0000] [26055] [INFO] Using worker: sync
[2019-01-10 00:29:03 +0000] [26059] [INFO] Booting worker with pid: 26059
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:33:34 +0000] [26055] [INFO] Handling signal: term
[2019-01-10 00:33:34 +0000] [26059] [INFO] Worker exiting (pid: 26059)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:33:34 +0000] [26055] [INFO] Shutting down: Master
[2019-01-10 00:33:34 +0000] [26068] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:33:34 +0000] [26068] [INFO] Listening at: http://127.0.0.1:8000 (26068)
[2019-01-10 00:33:34 +0000] [26068] [INFO] Using worker: sync
[2019-01-10 00:33:34 +0000] [26072] [INFO] Booting worker with pid: 26072
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:35:21 +0000] [26068] [INFO] Handling signal: term
[2019-01-10 00:35:21 +0000] [26072] [INFO] Worker exiting (pid: 26072)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:35:21 +0000] [26068] [INFO] Shutting down: Master
[2019-01-10 00:35:21 +0000] [26078] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:35:21 +0000] [26078] [INFO] Listening at: http://127.0.0.1:8000 (26078)
[2019-01-10 00:35:21 +0000] [26078] [INFO] Using worker: sync
[2019-01-10 00:35:21 +0000] [26082] [INFO] Booting worker with pid: 26082
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:48:05 +0000] [26078] [INFO] Handling signal: term
[2019-01-10 00:48:05 +0000] [26082] [INFO] Worker exiting (pid: 26082)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:48:05 +0000] [26078] [INFO] Shutting down: Master
[2019-01-10 00:48:05 +0000] [26098] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:48:05 +0000] [26098] [INFO] Listening at: http://127.0.0.1:8000 (26098)
[2019-01-10 00:48:05 +0000] [26098] [INFO] Using worker: sync
[2019-01-10 00:48:05 +0000] [26102] [INFO] Booting worker with pid: 26102
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:50:45 +0000] [26098] [INFO] Handling signal: term
[2019-01-10 00:50:45 +0000] [26102] [INFO] Worker exiting (pid: 26102)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:50:45 +0000] [26098] [INFO] Shutting down: Master
[2019-01-10 00:50:45 +0000] [26107] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:50:45 +0000] [26107] [INFO] Listening at: http://127.0.0.1:8000 (26107)
[2019-01-10 00:50:45 +0000] [26107] [INFO] Using worker: sync
[2019-01-10 00:50:45 +0000] [26111] [INFO] Booting worker with pid: 26111
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 00:52:29 +0000] [26107] [INFO] Handling signal: term
[2019-01-10 00:52:29 +0000] [26111] [INFO] Worker exiting (pid: 26111)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 00:52:29 +0000] [26107] [INFO] Shutting down: Master
[2019-01-10 00:52:29 +0000] [26117] [INFO] Starting gunicorn 19.9.0
[2019-01-10 00:52:29 +0000] [26117] [INFO] Listening at: http://127.0.0.1:8000 (26117)
[2019-01-10 00:52:29 +0000] [26117] [INFO] Using worker: sync
[2019-01-10 00:52:29 +0000] [26121] [INFO] Booting worker with pid: 26121
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:01:15 +0000] [26117] [INFO] Handling signal: term
[2019-01-10 01:01:15 +0000] [26121] [INFO] Worker exiting (pid: 26121)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:01:15 +0000] [26117] [INFO] Shutting down: Master
[2019-01-10 01:01:15 +0000] [26128] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:01:15 +0000] [26128] [INFO] Listening at: http://127.0.0.1:8000 (26128)
[2019-01-10 01:01:15 +0000] [26128] [INFO] Using worker: sync
[2019-01-10 01:01:15 +0000] [26132] [INFO] Booting worker with pid: 26132
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:06:58 +0000] [26128] [INFO] Handling signal: term
[2019-01-10 01:06:58 +0000] [26132] [INFO] Worker exiting (pid: 26132)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:06:58 +0000] [26128] [INFO] Shutting down: Master
[2019-01-10 01:06:58 +0000] [26160] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:06:58 +0000] [26160] [INFO] Listening at: http://127.0.0.1:8000 (26160)
[2019-01-10 01:06:58 +0000] [26160] [INFO] Using worker: sync
[2019-01-10 01:06:58 +0000] [26164] [INFO] Booting worker with pid: 26164
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:07:42 +0000] [26160] [INFO] Handling signal: term
[2019-01-10 01:07:42 +0000] [26164] [INFO] Worker exiting (pid: 26164)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:07:42 +0000] [26160] [INFO] Shutting down: Master
[2019-01-10 01:07:42 +0000] [26169] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:07:42 +0000] [26169] [INFO] Listening at: http://127.0.0.1:8000 (26169)
[2019-01-10 01:07:42 +0000] [26169] [INFO] Using worker: sync
[2019-01-10 01:07:42 +0000] [26173] [INFO] Booting worker with pid: 26173
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:13:42 +0000] [26169] [INFO] Handling signal: term
[2019-01-10 01:13:42 +0000] [26173] [INFO] Worker exiting (pid: 26173)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:13:42 +0000] [26169] [INFO] Shutting down: Master
[2019-01-10 01:13:42 +0000] [26179] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:13:42 +0000] [26179] [INFO] Listening at: http://127.0.0.1:8000 (26179)
[2019-01-10 01:13:42 +0000] [26179] [INFO] Using worker: sync
[2019-01-10 01:13:42 +0000] [26183] [INFO] Booting worker with pid: 26183
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:14:01 +0000] [26179] [INFO] Handling signal: term
[2019-01-10 01:14:01 +0000] [26183] [INFO] Worker exiting (pid: 26183)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:14:01 +0000] [26179] [INFO] Shutting down: Master
[2019-01-10 01:14:02 +0000] [26188] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:14:02 +0000] [26188] [INFO] Listening at: http://127.0.0.1:8000 (26188)
[2019-01-10 01:14:02 +0000] [26188] [INFO] Using worker: sync
[2019-01-10 01:14:02 +0000] [26192] [INFO] Booting worker with pid: 26192
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:18:28 +0000] [26188] [INFO] Handling signal: term
[2019-01-10 01:18:28 +0000] [26192] [INFO] Worker exiting (pid: 26192)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:18:28 +0000] [26188] [INFO] Shutting down: Master
[2019-01-10 01:18:29 +0000] [26201] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:18:29 +0000] [26201] [INFO] Listening at: http://127.0.0.1:8000 (26201)
[2019-01-10 01:18:29 +0000] [26201] [INFO] Using worker: sync
[2019-01-10 01:18:29 +0000] [26205] [INFO] Booting worker with pid: 26205
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:21:07 +0000] [26201] [INFO] Handling signal: term
[2019-01-10 01:21:07 +0000] [26205] [INFO] Worker exiting (pid: 26205)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:21:07 +0000] [26201] [INFO] Shutting down: Master
[2019-01-10 01:21:07 +0000] [26210] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:21:07 +0000] [26210] [INFO] Listening at: http://127.0.0.1:8000 (26210)
[2019-01-10 01:21:07 +0000] [26210] [INFO] Using worker: sync
[2019-01-10 01:21:07 +0000] [26214] [INFO] Booting worker with pid: 26214
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 01:21:27 +0000] [26210] [INFO] Handling signal: term
[2019-01-10 01:21:27 +0000] [26214] [INFO] Worker exiting (pid: 26214)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 01:21:27 +0000] [26210] [INFO] Shutting down: Master
[2019-01-10 01:21:27 +0000] [26219] [INFO] Starting gunicorn 19.9.0
[2019-01-10 01:21:27 +0000] [26219] [INFO] Listening at: http://127.0.0.1:8000 (26219)
[2019-01-10 01:21:27 +0000] [26219] [INFO] Using worker: sync
[2019-01-10 01:21:27 +0000] [26223] [INFO] Booting worker with pid: 26223
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 02:18:16 +0000] [26223] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-10 02:18:17 +0000] [26223] [INFO] Worker exiting (pid: 26223)
[2019-01-10 02:18:17 +0000] [26494] [INFO] Booting worker with pid: 26494
/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:794: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
[2019-01-10 02:30:54 +0000] [26219] [INFO] Handling signal: term
[2019-01-10 02:30:54 +0000] [26494] [INFO] Worker exiting (pid: 26494)
{u'id': 0}
{u'id': 0}
{u'id': 0}
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 02:30:54 +0000] [26219] [INFO] Shutting down: Master
[2019-01-10 02:30:55 +0000] [26508] [INFO] Starting gunicorn 19.9.0
[2019-01-10 02:30:55 +0000] [26508] [INFO] Listening at: http://127.0.0.1:8000 (26508)
[2019-01-10 02:30:55 +0000] [26508] [INFO] Using worker: sync
[2019-01-10 02:30:55 +0000] [26512] [INFO] Booting worker with pid: 26512
[2019-01-10 02:30:55 +0000] [26512] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-10 02:30:55 +0000] [26512] [INFO] Worker exiting (pid: 26512)
[2019-01-10 02:30:55 +0000] [26508] [INFO] Shutting down: Master
[2019-01-10 02:30:55 +0000] [26508] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 02:34:31 +0000] [26535] [INFO] Starting gunicorn 19.9.0
[2019-01-10 02:34:31 +0000] [26535] [INFO] Listening at: http://127.0.0.1:8000 (26535)
[2019-01-10 02:34:31 +0000] [26535] [INFO] Using worker: sync
[2019-01-10 02:34:31 +0000] [26539] [INFO] Booting worker with pid: 26539
[2019-01-10 02:34:31 +0000] [26539] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-10 02:34:31 +0000] [26539] [INFO] Worker exiting (pid: 26539)
[2019-01-10 02:34:31 +0000] [26535] [INFO] Shutting down: Master
[2019-01-10 02:34:31 +0000] [26535] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 02:35:10 +0000] [26556] [INFO] Starting gunicorn 19.9.0
[2019-01-10 02:35:10 +0000] [26556] [INFO] Listening at: http://127.0.0.1:8000 (26556)
[2019-01-10 02:35:10 +0000] [26556] [INFO] Using worker: sync
[2019-01-10 02:35:10 +0000] [26560] [INFO] Booting worker with pid: 26560
[2019-01-10 02:35:10 +0000] [26560] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-10 02:35:10 +0000] [26560] [INFO] Worker exiting (pid: 26560)
[2019-01-10 02:35:10 +0000] [26556] [INFO] Shutting down: Master
[2019-01-10 02:35:10 +0000] [26556] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 02:35:35 +0000] [26565] [INFO] Starting gunicorn 19.9.0
[2019-01-10 02:35:35 +0000] [26565] [INFO] Listening at: http://127.0.0.1:8000 (26565)
[2019-01-10 02:35:35 +0000] [26565] [INFO] Using worker: sync
[2019-01-10 02:35:35 +0000] [26569] [INFO] Booting worker with pid: 26569
[2019-01-10 02:35:35 +0000] [26569] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-10 02:35:35 +0000] [26569] [INFO] Worker exiting (pid: 26569)
[2019-01-10 02:35:35 +0000] [26565] [INFO] Shutting down: Master
[2019-01-10 02:35:35 +0000] [26565] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 02:37:07 +0000] [26585] [INFO] Starting gunicorn 19.9.0
[2019-01-10 02:37:07 +0000] [26585] [INFO] Listening at: http://127.0.0.1:8000 (26585)
[2019-01-10 02:37:07 +0000] [26585] [INFO] Using worker: sync
[2019-01-10 02:37:07 +0000] [26589] [INFO] Booting worker with pid: 26589
[2019-01-10 02:37:07 +0000] [26589] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-10 02:37:07 +0000] [26589] [INFO] Worker exiting (pid: 26589)
[2019-01-10 02:37:07 +0000] [26585] [INFO] Shutting down: Master
[2019-01-10 02:37:07 +0000] [26585] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 02:37:22 +0000] [26594] [INFO] Starting gunicorn 19.9.0
[2019-01-10 02:37:22 +0000] [26594] [INFO] Listening at: http://127.0.0.1:8000 (26594)
[2019-01-10 02:37:22 +0000] [26594] [INFO] Using worker: sync
[2019-01-10 02:37:22 +0000] [26598] [INFO] Booting worker with pid: 26598
[2019-01-10 02:37:22 +0000] [26598] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-10 02:37:22 +0000] [26598] [INFO] Worker exiting (pid: 26598)
[2019-01-10 02:37:22 +0000] [26594] [INFO] Shutting down: Master
[2019-01-10 02:37:22 +0000] [26594] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 23:17:11 +0000] [32595] [INFO] Starting gunicorn 19.9.0
[2019-01-10 23:17:11 +0000] [32595] [INFO] Listening at: http://127.0.0.1:8000 (32595)
[2019-01-10 23:17:11 +0000] [32595] [INFO] Using worker: sync
[2019-01-10 23:17:11 +0000] [32599] [INFO] Booting worker with pid: 32599
[2019-01-10 23:19:40 +0000] [32599] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-10 23:19:41 +0000] [32599] [INFO] Worker exiting (pid: 32599)
[2019-01-10 23:19:41 +0000] [32622] [INFO] Booting worker with pid: 32622
[2019-01-10 23:20:24 +0000] [32622] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-10 23:20:26 +0000] [32622] [INFO] Worker exiting (pid: 32622)
[2019-01-10 23:20:26 +0000] [32642] [INFO] Booting worker with pid: 32642
[2019-01-10 23:25:36 +0000] [32642] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-10 23:25:42 +0000] [32642] [INFO] Worker exiting (pid: 32642)
[2019-01-10 23:25:42 +0000] [32690] [INFO] Booting worker with pid: 32690
[2019-01-10 23:46:13 +0000] [32690] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-10 23:46:13 +0000] [32690] [INFO] Worker exiting (pid: 32690)
[2019-01-10 23:46:13 +0000] [420] [INFO] Booting worker with pid: 420
[2019-01-10 23:48:14 +0000] [420] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-10 23:48:29 +0000] [420] [INFO] Worker exiting (pid: 420)
[2019-01-10 23:48:29 +0000] [425] [INFO] Booting worker with pid: 425
[2019-01-10 23:48:29 +0000] [425] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 36, in <module>
    import models
  File "/home/ubuntu/git/dotter/models.py", line 14, in <module>
    class line(db.Model):
  File "/home/ubuntu/git/dotter/models.py", line 24, in line
    check     = db.Column(Boolean, unique=False, default=True)
NameError: name 'Boolean' is not defined
[2019-01-10 23:48:29 +0000] [425] [INFO] Worker exiting (pid: 425)
[2019-01-10 23:48:29 +0000] [32595] [INFO] Shutting down: Master
[2019-01-10 23:48:29 +0000] [32595] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 23:54:39 +0000] [476] [INFO] Starting gunicorn 19.9.0
[2019-01-10 23:54:39 +0000] [476] [INFO] Listening at: http://127.0.0.1:8000 (476)
[2019-01-10 23:54:39 +0000] [476] [INFO] Using worker: sync
[2019-01-10 23:54:39 +0000] [480] [INFO] Booting worker with pid: 480
[2019-01-10 23:59:00 +0000] [480] [INFO] Worker reloading: /home/ubuntu/git/dotter/config.py modified
[2019-01-10 23:59:10 +0000] [480] [INFO] Worker exiting (pid: 480)
[2019-01-10 23:59:10 +0000] [522] [INFO] Booting worker with pid: 522
[2019-01-10 23:59:52 +0000] [476] [INFO] Handling signal: term
[2019-01-10 23:59:52 +0000] [522] [INFO] Worker exiting (pid: 522)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-10 23:59:52 +0000] [476] [INFO] Shutting down: Master
[2019-01-10 23:59:52 +0000] [551] [INFO] Starting gunicorn 19.9.0
[2019-01-10 23:59:52 +0000] [551] [INFO] Listening at: http://127.0.0.1:8000 (551)
[2019-01-10 23:59:52 +0000] [551] [INFO] Using worker: sync
[2019-01-10 23:59:52 +0000] [555] [INFO] Booting worker with pid: 555
[2019-01-11 00:02:06 +0000] [555] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-11 00:02:07 +0000] [555] [INFO] Worker exiting (pid: 555)
[2019-01-11 00:02:07 +0000] [564] [INFO] Booting worker with pid: 564
[2019-01-11 00:12:53 +0000] [564] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-11 00:12:53 +0000] [564] [INFO] Worker exiting (pid: 564)
[2019-01-11 00:12:53 +0000] [664] [INFO] Booting worker with pid: 664
[2019-01-11 00:13:15 +0000] [664] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-11 00:13:24 +0000] [664] [INFO] Worker exiting (pid: 664)
[2019-01-11 00:13:24 +0000] [675] [INFO] Booting worker with pid: 675
[2019-01-11 00:15:17 +0000] [675] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-11 00:15:24 +0000] [675] [INFO] Worker exiting (pid: 675)
[2019-01-11 00:15:24 +0000] [696] [INFO] Booting worker with pid: 696
[2019-01-11 00:15:52 +0000] [696] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-11 00:15:54 +0000] [696] [INFO] Worker exiting (pid: 696)
[2019-01-11 00:15:54 +0000] [704] [INFO] Booting worker with pid: 704
[2019-01-11 00:18:39 +0000] [704] [INFO] Worker reloading: /home/ubuntu/git/dotter/config.py modified
[2019-01-11 00:18:40 +0000] [704] [INFO] Worker exiting (pid: 704)
[2019-01-11 00:18:40 +0000] [765] [INFO] Booting worker with pid: 765
[2019-01-11 00:18:43 +0000] [551] [INFO] Handling signal: term
[2019-01-11 00:18:43 +0000] [765] [INFO] Worker exiting (pid: 765)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-11 00:18:43 +0000] [551] [INFO] Shutting down: Master
[2019-01-11 00:18:43 +0000] [773] [INFO] Starting gunicorn 19.9.0
[2019-01-11 00:18:43 +0000] [773] [INFO] Listening at: http://127.0.0.1:8000 (773)
[2019-01-11 00:18:43 +0000] [773] [INFO] Using worker: sync
[2019-01-11 00:18:43 +0000] [777] [INFO] Booting worker with pid: 777
[2019-01-11 00:24:54 +0000] [777] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-11 00:25:05 +0000] [777] [INFO] Worker exiting (pid: 777)
[2019-01-11 00:25:05 +0000] [864] [INFO] Booting worker with pid: 864
[2019-01-11 02:37:51 +0000] [864] [INFO] Worker reloading: /home/ubuntu/git/dotter/models.py modified
[2019-01-11 02:37:59 +0000] [864] [INFO] Worker exiting (pid: 864)
[2019-01-11 02:37:59 +0000] [925] [INFO] Booting worker with pid: 925
[2019-01-11 06:10:33 +0000] [925] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-11 06:10:48 +0000] [925] [INFO] Worker exiting (pid: 925)
[2019-01-11 06:10:48 +0000] [1594] [INFO] Booting worker with pid: 1594
[2019-01-11 06:10:48 +0000] [1594] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 98, in <module>
    @app.route("/lines_id", methods=["GET", "POST"])
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: get_lines_id
[2019-01-11 06:10:48 +0000] [1594] [INFO] Worker exiting (pid: 1594)
[2019-01-11 06:10:48 +0000] [773] [INFO] Shutting down: Master
[2019-01-11 06:10:48 +0000] [773] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-11 06:34:44 +0000] [2388] [INFO] Starting gunicorn 19.9.0
[2019-01-11 06:34:44 +0000] [2388] [INFO] Listening at: http://127.0.0.1:8000 (2388)
[2019-01-11 06:34:44 +0000] [2388] [INFO] Using worker: sync
[2019-01-11 06:34:44 +0000] [2392] [INFO] Booting worker with pid: 2392
[2019-01-11 06:34:45 +0000] [2392] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 102, in <module>
    @app.route("/lines_id", methods=["GET", "POST"])
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: get_lines_id
[2019-01-11 06:34:45 +0000] [2392] [INFO] Worker exiting (pid: 2392)
[2019-01-11 06:34:45 +0000] [2388] [INFO] Shutting down: Master
[2019-01-11 06:34:45 +0000] [2388] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-11 06:35:38 +0000] [2408] [INFO] Starting gunicorn 19.9.0
[2019-01-11 06:35:38 +0000] [2408] [INFO] Listening at: http://127.0.0.1:8000 (2408)
[2019-01-11 06:35:38 +0000] [2408] [INFO] Using worker: sync
[2019-01-11 06:35:38 +0000] [2412] [INFO] Booting worker with pid: 2412
[2019-01-11 06:35:53,354] ERROR in app: Exception on /get_books [GET]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 99, in get_books
    books = db.books.query.all()
AttributeError: 'SQLAlchemy' object has no attribute 'books'
[2019-01-11 06:36:44,133] ERROR in app: Exception on /get_books [GET]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 99, in get_books
    books = db.books.query.all()
AttributeError: 'SQLAlchemy' object has no attribute 'books'
[2019-01-11 06:36:59 +0000] [2412] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-11 06:37:03 +0000] [2412] [INFO] Worker exiting (pid: 2412)
[2019-01-11 06:37:03 +0000] [2415] [INFO] Booting worker with pid: 2415
[2019-01-11 06:37:04,252] ERROR in app: Exception on /get_books [GET]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 99, in get_books
    books = db.books.query.all()
AttributeError: 'SQLAlchemy' object has no attribute 'books'
[2019-01-11 06:37:09 +0000] [2408] [INFO] Handling signal: term
[2019-01-11 06:37:09 +0000] [2415] [INFO] Worker exiting (pid: 2415)
[2019-01-11 06:37:09 +0000] [2408] [INFO] Shutting down: Master
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-11 07:06:53 +0000] [2529] [INFO] Starting gunicorn 19.9.0
[2019-01-11 07:06:53 +0000] [2529] [INFO] Listening at: http://127.0.0.1:8000 (2529)
[2019-01-11 07:06:53 +0000] [2529] [INFO] Using worker: sync
[2019-01-11 07:06:53 +0000] [2533] [INFO] Booting worker with pid: 2533
[2019-01-11 07:16:35 +0000] [2533] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-11 07:16:39 +0000] [2533] [INFO] Worker exiting (pid: 2533)
[2019-01-11 07:16:39 +0000] [2663] [INFO] Booting worker with pid: 2663
[2019-01-11 07:16:47,006] ERROR in app: Exception on /lines [GET]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 50, in get_lines
    days = [d.json for d in day.query.all]
TypeError: 'instancemethod' object is not iterable
[2019-01-11 07:17:22 +0000] [2663] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-11 07:17:24 +0000] [2663] [INFO] Worker exiting (pid: 2663)
[2019-01-11 07:17:24 +0000] [2669] [INFO] Booting worker with pid: 2669
[2019-01-11 07:17:24,612] ERROR in app: Exception on /lines [GET]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 88, in get_lines
    days = [d.json for d in day.query.all]*2
TypeError: 'instancemethod' object is not iterable
[2019-01-11 07:17:25,856] ERROR in app: Exception on /lines [GET]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 88, in get_lines
    days = [d.json for d in day.query.all]*2
TypeError: 'instancemethod' object is not iterable
[2019-01-11 07:17:57 +0000] [2669] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-11 07:17:59 +0000] [2669] [INFO] Worker exiting (pid: 2669)
[2019-01-11 07:17:59 +0000] [2672] [INFO] Booting worker with pid: 2672
[2019-01-11 07:18:00,143] ERROR in app: Exception on /lines [GET]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 88, in get_lines
    days = [d.json for d in day.query.all]*2
TypeError: 'instancemethod' object is not iterable
[2019-01-11 07:18:13 +0000] [2529] [INFO] Handling signal: term
[2019-01-11 07:18:13 +0000] [2672] [INFO] Worker exiting (pid: 2672)
[2019-01-11 07:18:13 +0000] [2529] [INFO] Shutting down: Master
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-11 08:56:02 +0000] [2925] [INFO] Starting gunicorn 19.9.0
[2019-01-11 08:56:02 +0000] [2925] [INFO] Listening at: http://127.0.0.1:8000 (2925)
[2019-01-11 08:56:02 +0000] [2925] [INFO] Using worker: sync
[2019-01-11 08:56:02 +0000] [2929] [INFO] Booting worker with pid: 2929
============= DAY1 ============= 
[{'user_id': 1, 'text': u'the different possible points are', 'id': 1, 'day_id': 1, 'parent_id': 0, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'a box to indicate a task to finish', 'id': 2, 'day_id': 1, 'parent_id': 1, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'a solid dot to indicate a note', 'id': 3, 'day_id': 1, 'parent_id': 1, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'a circle to indicate a meeting', 'id': 4, 'day_id': 1, 'parent_id': 1, 'shape': 1, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'each line has a range of options when hovered over', 'id': 5, 'day_id': 1, 'parent_id': 0, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u"the 'x' deletes the lines and everything below", 'id': 6, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u"the '!' adds an indicator to emphasize importance/whatever", 'id': 7, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': True, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'the box/dot/circle indicate how the point should function', 'id': 8, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'the boxes can be checked and unchecked', 'id': 9, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'the arrow changes the point between box/dot/circle', 'id': 10, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u"the '+' adds a child line to the current point", 'id': 11, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'settings are kept at the top and bottom of each page', 'id': 12, 'day_id': 1, 'parent_id': 0, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}]
============= DAY2 ============= 
[{'user_id': 1, 'text': u'functional UI interactions', 'id': 13, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'naming for simple JavaScript functionality', 'id': 14, 'day_id': 2, 'parent_id': 13, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'make days collapsible', 'id': 15, 'day_id': 2, 'parent_id': 13, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'add landing page for login/displaying books', 'id': 16, 'day_id': 2, 'parent_id': 13, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'convert site to run on VPS', 'id': 17, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'remove PHP to convert to Python/Flask', 'id': 18, 'day_id': 2, 'parent_id': 17, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'install nginx/Flask/etc.', 'id': 19, 'day_id': 2, 'parent_id': 17, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'build templates in Flask', 'id': 20, 'day_id': 2, 'parent_id': 17, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'establish Flask / JavaScript interactions', 'id': 21, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'send JSON from flask', 'id': 22, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'receive JSON in JavaScript', 'id': 23, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'build html from JSON on client-side JavaScript', 'id': 24, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'read JavaScript JSON on server-side in Flask', 'id': 25, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'build Flask database system w/ mysql (or potentially other db management)', 'id': 26, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'establish db layout', 'id': 27, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'build Flask functions to read/write to db', 'id': 28, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'read user data to send to JS on clientside', 'id': 29, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'write to db from JSON on clientside', 'id': 30, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'add user login', 'id': 31, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'probably want limited users due to small VPS currently', 'id': 32, 'day_id': 2, 'parent_id': 31, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'may want to wait till fully functional to open up to outside users for testing', 'id': 33, 'day_id': 2, 'parent_id': 31, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'legitimize site', 'id': 34, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'get domain name', 'id': 35, 'day_id': 2, 'parent_id': 34, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'dotter.app', 'id': 36, 'day_id': 2, 'parent_id': 34, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'make ssl certs work in nginx', 'id': 37, 'day_id': 2, 'parent_id': 34, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}]
============= DAY1 ============= 
[{'user_id': 1, 'text': u'the different possible points are', 'id': 1, 'day_id': 1, 'parent_id': 0, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'a box to indicate a task to finish', 'id': 2, 'day_id': 1, 'parent_id': 1, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'a solid dot to indicate a note', 'id': 3, 'day_id': 1, 'parent_id': 1, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'a circle to indicate a meeting', 'id': 4, 'day_id': 1, 'parent_id': 1, 'shape': 1, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'each line has a range of options when hovered over', 'id': 5, 'day_id': 1, 'parent_id': 0, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u"the 'x' deletes the lines and everything below", 'id': 6, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u"the '!' adds an indicator to emphasize importance/whatever", 'id': 7, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': True, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'the box/dot/circle indicate how the point should function', 'id': 8, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'the boxes can be checked and unchecked', 'id': 9, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'the arrow changes the point between box/dot/circle', 'id': 10, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u"the '+' adds a child line to the current point", 'id': 11, 'day_id': 1, 'parent_id': 5, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'settings are kept at the top and bottom of each page', 'id': 12, 'day_id': 1, 'parent_id': 0, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}]
============= DAY2 ============= 
[{'user_id': 1, 'text': u'functional UI interactions', 'id': 13, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'naming for simple JavaScript functionality', 'id': 14, 'day_id': 2, 'parent_id': 13, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'make days collapsible', 'id': 15, 'day_id': 2, 'parent_id': 13, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'add landing page for login/displaying books', 'id': 16, 'day_id': 2, 'parent_id': 13, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'convert site to run on VPS', 'id': 17, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'remove PHP to convert to Python/Flask', 'id': 18, 'day_id': 2, 'parent_id': 17, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'install nginx/Flask/etc.', 'id': 19, 'day_id': 2, 'parent_id': 17, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'build templates in Flask', 'id': 20, 'day_id': 2, 'parent_id': 17, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'establish Flask / JavaScript interactions', 'id': 21, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'send JSON from flask', 'id': 22, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'receive JSON in JavaScript', 'id': 23, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'build html from JSON on client-side JavaScript', 'id': 24, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'read JavaScript JSON on server-side in Flask', 'id': 25, 'day_id': 2, 'parent_id': 21, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'build Flask database system w/ mysql (or potentially other db management)', 'id': 26, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'establish db layout', 'id': 27, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'build Flask functions to read/write to db', 'id': 28, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'read user data to send to JS on clientside', 'id': 29, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'write to db from JSON on clientside', 'id': 30, 'day_id': 2, 'parent_id': 26, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'add user login', 'id': 31, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'probably want limited users due to small VPS currently', 'id': 32, 'day_id': 2, 'parent_id': 31, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'may want to wait till fully functional to open up to outside users for testing', 'id': 33, 'day_id': 2, 'parent_id': 31, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'legitimize site', 'id': 34, 'day_id': 2, 'parent_id': 0, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'get domain name', 'id': 35, 'day_id': 2, 'parent_id': 34, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}, {'user_id': 1, 'text': u'dotter.app', 'id': 36, 'day_id': 2, 'parent_id': 34, 'shape': 2, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': False}, {'user_id': 1, 'text': u'make ssl certs work in n[2019-01-11 08:58:14 +0000] [2929] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-11 08:58:14 +0000] [2929] [INFO] Worker exiting (pid: 2929)
ginx', 'id': 37, 'day_id': 2, 'parent_id': 34, 'shape': 0, 'important': False, 'book_id': 1, 'date_complete': u'12/12/2018', 'date': u'12/12/2018', 'check': True}]
[2019-01-11 08:58:14 +0000] [2932] [INFO] Booting worker with pid: 2932
[2019-01-11 09:13:19 +0000] [2925] [INFO] Handling signal: term
[2019-01-11 09:13:19 +0000] [2932] [INFO] Worker exiting (pid: 2932)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-11 09:13:19 +0000] [2925] [INFO] Shutting down: Master
[2019-01-11 09:13:19 +0000] [2944] [INFO] Starting gunicorn 19.9.0
[2019-01-11 09:13:19 +0000] [2944] [INFO] Listening at: http://127.0.0.1:8000 (2944)
[2019-01-11 09:13:19 +0000] [2944] [INFO] Using worker: sync
[2019-01-11 09:13:19 +0000] [2948] [INFO] Booting worker with pid: 2948
[2019-01-11 17:48:35 +0000] [2944] [INFO] Handling signal: term
[2019-01-11 17:48:35 +0000] [2948] [INFO] Worker exiting (pid: 2948)
[2019-01-11 17:48:35 +0000] [2944] [INFO] Shutting down: Master
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 05:22:35 +0000] [5911] [INFO] Starting gunicorn 19.9.0
[2019-01-12 05:22:35 +0000] [5911] [INFO] Listening at: http://127.0.0.1:8000 (5911)
[2019-01-12 05:22:35 +0000] [5911] [INFO] Using worker: sync
[2019-01-12 05:22:35 +0000] [5915] [INFO] Booting worker with pid: 5915
[2019-01-12 05:22:40 +0000] [5911] [INFO] Handling signal: hup
[2019-01-12 05:22:40 +0000] [5911] [INFO] Hang up: Master
[2019-01-12 05:22:40 +0000] [5919] [INFO] Booting worker with pid: 5919
[2019-01-12 05:25:52,818] ERROR in app: Exception on /delete_book [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/git/dotter/app.py", line 122, in delete_book
    print current_user.is_authenticated, current_user.id,  book.query.filter_by(id=request.get_json()['id']).first().id
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2895, in first
    ret = list(self[0:1])
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
    return list(res)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
InterfaceError: <unprintable InterfaceError object>
[2019-01-12 17:38:34 +0000] [5919] [INFO] Worker exiting (pid: 5919)
getting day 1
deleting book {u'isTrusted': True}
True 1 getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 17:38:34 +0000] [5911] [INFO] Handling signal: term
[2019-01-12 17:38:35 +0000] [5911] [INFO] Shutting down: Master
[2019-01-12 17:38:35 +0000] [7472] [INFO] Starting gunicorn 19.9.0
[2019-01-12 17:38:35 +0000] [7472] [INFO] Listening at: http://127.0.0.1:8000 (7472)
[2019-01-12 17:38:35 +0000] [7472] [INFO] Using worker: sync
[2019-01-12 17:38:35 +0000] [7476] [INFO] Booting worker with pid: 7476
[2019-01-12 17:38:35 +0000] [7476] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 8, in <module>
    from flask_sqlalchemy import SQLAlchemy
ImportError: No module named flask_sqlalchemy
[2019-01-12 17:38:35 +0000] [7476] [INFO] Worker exiting (pid: 7476)
[2019-01-12 17:38:35 +0000] [7472] [INFO] Shutting down: Master
[2019-01-12 17:38:35 +0000] [7472] [INFO] Reason: Worker failed to boot.
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 17:38:58 +0000] [7495] [INFO] Starting gunicorn 19.9.0
[2019-01-12 17:38:58 +0000] [7495] [INFO] Listening at: http://127.0.0.1:8000 (7495)
[2019-01-12 17:38:58 +0000] [7495] [INFO] Using worker: sync
[2019-01-12 17:38:58 +0000] [7499] [INFO] Booting worker with pid: 7499
[2019-01-12 18:07:51 +0000] [7495] [INFO] Handling signal: term
[2019-01-12 18:07:51 +0000] [7499] [INFO] Worker exiting (pid: 7499)
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 18:07:51 +0000] [7495] [INFO] Shutting down: Master
[2019-01-12 18:07:52 +0000] [7519] [INFO] Starting gunicorn 19.9.0
[2019-01-12 18:07:52 +0000] [7519] [INFO] Listening at: http://127.0.0.1:8000 (7519)
[2019-01-12 18:07:52 +0000] [7519] [INFO] Using worker: sync
[2019-01-12 18:07:52 +0000] [7523] [INFO] Booting worker with pid: 7523
[2019-01-12 20:49:29 +0000] [7519] [INFO] Handling signal: term
[2019-01-12 20:49:29 +0000] [7523] [INFO] Worker exiting (pid: 7523)
getting day 1
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 20:49:29 +0000] [7519] [INFO] Shutting down: Master
[2019-01-12 20:49:29 +0000] [7610] [INFO] Starting gunicorn 19.9.0
[2019-01-12 20:49:29 +0000] [7610] [INFO] Listening at: http://127.0.0.1:8000 (7610)
[2019-01-12 20:49:29 +0000] [7610] [INFO] Using worker: sync
[2019-01-12 20:49:29 +0000] [7614] [INFO] Booting worker with pid: 7614
[2019-01-12 21:09:36 +0000] [7610] [INFO] Handling signal: term
[2019-01-12 21:09:36 +0000] [7614] [INFO] Worker exiting (pid: 7614)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 21:09:36 +0000] [7610] [INFO] Shutting down: Master
[2019-01-12 21:09:36 +0000] [7638] [INFO] Starting gunicorn 19.9.0
[2019-01-12 21:09:36 +0000] [7638] [INFO] Listening at: http://127.0.0.1:8000 (7638)
[2019-01-12 21:09:36 +0000] [7638] [INFO] Using worker: sync
[2019-01-12 21:09:36 +0000] [7642] [INFO] Booting worker with pid: 7642
[2019-01-12 21:10:19 +0000] [7638] [INFO] Handling signal: term
[2019-01-12 21:10:19 +0000] [7642] [INFO] Worker exiting (pid: 7642)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 21:10:19 +0000] [7638] [INFO] Shutting down: Master
[2019-01-12 21:10:19 +0000] [7647] [INFO] Starting gunicorn 19.9.0
[2019-01-12 21:10:19 +0000] [7647] [INFO] Listening at: http://127.0.0.1:8000 (7647)
[2019-01-12 21:10:19 +0000] [7647] [INFO] Using worker: sync
[2019-01-12 21:10:19 +0000] [7651] [INFO] Booting worker with pid: 7651
[2019-01-12 21:10:50 +0000] [7647] [INFO] Handling signal: term
[2019-01-12 21:10:50 +0000] [7651] [INFO] Worker exiting (pid: 7651)
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 21:10:50 +0000] [7647] [INFO] Shutting down: Master
[2019-01-12 21:10:50 +0000] [7656] [INFO] Starting gunicorn 19.9.0
[2019-01-12 21:10:50 +0000] [7656] [INFO] Listening at: http://127.0.0.1:8000 (7656)
[2019-01-12 21:10:50 +0000] [7656] [INFO] Using worker: sync
[2019-01-12 21:10:50 +0000] [7660] [INFO] Booting worker with pid: 7660
[2019-01-12 21:36:18 +0000] [7656] [INFO] Handling signal: term
[2019-01-12 21:36:18 +0000] [7660] [INFO] Worker exiting (pid: 7660)
True
adding new book cookbook True True
deleting book 2
True 1 2
False
adding new book cookbook False False
deleting book 2
True 1 2
True
adding new book cookbook True True
deleting book 2
True 1 2
False
adding new book cookbook False False
deleting book 2
True 1 2
False
adding new book cookbook False False
deleting book 2
True 1 2
False
adding new book grocery list False False
deleting book 2
True 1 2
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
True
adding new book  True True
deleting book 2
True 1 2
False
adding new book implementation to-do list False False
deleting book 2
True 1 2
getting day 1
getting day 1
getting day 1
getting day 1
False
adding new book cookbook False False
getting day 1
getting day 1
deleting book 2
True 1 2
getting day 1
getting day 1
getting day 1
getting day 1
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 21:36:18 +0000] [7656] [INFO] Shutting down: Master
[2019-01-12 21:36:18 +0000] [7769] [INFO] Starting gunicorn 19.9.0
[2019-01-12 21:36:18 +0000] [7769] [INFO] Listening at: http://127.0.0.1:8000 (7769)
[2019-01-12 21:36:18 +0000] [7769] [INFO] Using worker: sync
[2019-01-12 21:36:18 +0000] [7773] [INFO] Booting worker with pid: 7773
[2019-01-12 21:36:47 +0000] [7769] [INFO] Handling signal: term
[2019-01-12 21:36:47 +0000] [7773] [INFO] Worker exiting (pid: 7773)
getting day 1
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 21:36:47 +0000] [7769] [INFO] Shutting down: Master
[2019-01-12 21:36:47 +0000] [7778] [INFO] Starting gunicorn 19.9.0
[2019-01-12 21:36:47 +0000] [7778] [INFO] Listening at: http://127.0.0.1:8000 (7778)
[2019-01-12 21:36:47 +0000] [7778] [INFO] Using worker: sync
[2019-01-12 21:36:47 +0000] [7782] [INFO] Booting worker with pid: 7782
[2019-01-12 22:05:32 +0000] [7778] [INFO] Handling signal: term
[2019-01-12 22:05:32 +0000] [7782] [INFO] Worker exiting (pid: 7782)
getting day 1
getting day 1
getting day 1
False
adding new book cookbook False False
getting day 2
getting day 2
getting day 2
getting day 2
getting day 1
getting day 1
getting day 1
getting day 1
getting day 2
getting day 1
getting day 2
getting day 1
getting day 2
getting day 1
deleting book 2
True 1 2
getting day 1
False
adding new book dotter todo list False False
getting day 1
getting day 1
deleting book 2
True 1 2
getting day 2
getting day 1
getting day 2
getting day 2
getting day 1
getting day 2
True
adding new book  True True
deleting book 3
True 1 3
False
adding new book cookbook False False
getting day 2
getting day 2
getting day 1
getting day 2
deleting book 3
True 1 3
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 2
getting day 2
getting day 1
getting day 2
getting day 2
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 22:05:32 +0000] [7778] [INFO] Shutting down: Master
[2019-01-12 22:05:33 +0000] [7819] [INFO] Starting gunicorn 19.9.0
[2019-01-12 22:05:33 +0000] [7819] [INFO] Listening at: http://127.0.0.1:8000 (7819)
[2019-01-12 22:05:33 +0000] [7819] [INFO] Using worker: sync
[2019-01-12 22:05:33 +0000] [7823] [INFO] Booting worker with pid: 7823
[2019-01-12 22:16:09 +0000] [7819] [INFO] Handling signal: term
[2019-01-12 22:16:09 +0000] [7823] [INFO] Worker exiting (pid: 7823)
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
getting day 2
getting day 2
getting day 1
getting day 2
getting day 1
getting day 2
getting day 1
getting day 2
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-12 22:16:09 +0000] [7819] [INFO] Shutting down: Master
[2019-01-12 22:16:09 +0000] [7831] [INFO] Starting gunicorn 19.9.0
[2019-01-12 22:16:09 +0000] [7831] [INFO] Listening at: http://127.0.0.1:8000 (7831)
[2019-01-12 22:16:09 +0000] [7831] [INFO] Using worker: sync
[2019-01-12 22:16:09 +0000] [7835] [INFO] Booting worker with pid: 7835
[2019-01-13 04:02:38 +0000] [7831] [INFO] Handling signal: hup
[2019-01-13 04:02:38 +0000] [7831] [INFO] Hang up: Master
[2019-01-13 04:02:38 +0000] [7994] [INFO] Booting worker with pid: 7994
[2019-01-13 22:33:29 +0000] [7994] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-13 22:33:31 +0000] [7994] [INFO] Worker exiting (pid: 7994)
deleting book 3
True 1 3
deleting book 4
True 1 4
getting day 1
getting day 2
getting day 1
getting day 2
getting day 1
getting day 2
getting day 1
getting day 1
getting day 1
getting day 1
getting day 1
False
adding new book Cookbook False False
deleting book 3
True 1 3
True
adding new book Cookbook True True
getting day 2
getting day 1
getting day 1
getting day 2
getting day 3
getting day 3
deleting book 3
True 1 3
getting day 1
[2019-01-13 22:33:31 +0000] [14762] [INFO] Booting worker with pid: 14762
[2019-01-13 22:37:58 +0000] [14762] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-13 22:38:02 +0000] [14762] [INFO] Worker exiting (pid: 14762)
[2019-01-13 22:38:02 +0000] [14801] [INFO] Booting worker with pid: 14801
[2019-01-13 22:38:02 +0000] [14801] [ERROR] invalid syntax (app.py, line 123)
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 123
    d = day(title=d['title'], date=b.date, user_id=u.id, book_id=b.id))
                                                                      ^
SyntaxError: invalid syntax
[2019-01-13 22:38:04 +0000] [14801] [INFO] Worker reloading: /home/ubuntu/git/dotter/app.py modified
[2019-01-13 22:38:05 +0000] [14801] [INFO] Worker exiting (pid: 14801)
[2019-01-13 22:38:05 +0000] [14803] [INFO] Booting worker with pid: 14803
[2019-01-13 22:38:05 +0000] [14803] [ERROR] invalid syntax (app.py, line 123)
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 123
    d = day(title=d['title'], date=b.date, user_id=u.id, book_id=b.id))
                                                                      ^
SyntaxError: invalid syntax
[2019-01-13 22:41:05 +0000] [7831] [INFO] Handling signal: term
[2019-01-13 22:41:05 +0000] [14803] [INFO] Worker exiting (pid: 14803)
[2019-01-13 22:41:05 +0000] [7831] [INFO] Shutting down: Master
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-13 22:41:06 +0000] [14823] [INFO] Starting gunicorn 19.9.0
[2019-01-13 22:41:06 +0000] [14823] [INFO] Listening at: http://127.0.0.1:8000 (14823)
[2019-01-13 22:41:06 +0000] [14823] [INFO] Using worker: sync
[2019-01-13 22:41:06 +0000] [14827] [INFO] Booting worker with pid: 14827
[2019-01-13 22:41:06 +0000] [14827] [ERROR] invalid syntax (app.py, line 123)
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/home/ubuntu/git/dotter/app.py", line 123
    d = day(title=d['title'], date=b.date, user_id=u.id, book_id=b.id))
                                                                      ^
SyntaxError: invalid syntax
[2019-01-13 22:41:17 +0000] [14823] [INFO] Handling signal: term
[2019-01-13 22:41:17 +0000] [14827] [INFO] Worker exiting (pid: 14827)
[2019-01-13 22:41:17 +0000] [14823] [INFO] Shutting down: Master
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-17 11:05:16 +0000] [23290] [INFO] Starting gunicorn 19.9.0
[2019-01-17 11:05:16 +0000] [23290] [INFO] Listening at: http://127.0.0.1:8000 (23290)
[2019-01-17 11:05:16 +0000] [23290] [INFO] Using worker: sync
[2019-01-17 11:05:16 +0000] [23295] [INFO] Booting worker with pid: 23295
[2019-01-17 11:40:52,551] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 11:40:58,142] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 11:41:05,181] ERROR in app: Exception on /update_title [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 12:34:53,715] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 12:44:49 +0000] [23290] [INFO] Handling signal: term
[2019-01-17 12:44:49 +0000] [23295] [INFO] Worker exiting (pid: 23295)
getting day 5
getting day 3
getting day 5
getting day 5
getting day 5
getting day 5
getting day 4
adding new line to day 5 line 0
commited session
161 <class 'models.line'>
updating line: shampoo<br>
adding new line to day 5 line 0
commited session
adding new line to day 5 line 0
commited session
deleting line 163
162 <class 'models.line'>
updating line: deodorant<br>
5 groceries shopping stuff
updating title: shopping stuff
getting day 4
getting day 3
getting day 1
getting day 2
getting day 5
getting day 5
getting day 5
{u'id': u'6', u'collapse': False}
{u'id': u'6', u'collapse': True}
{u'id': u'6', u'collapse': False}
{u'id': u'6', u'collapse': True}
getting day 5
160 <class 'models.line'>
updating line: make sure it's very clear what the importance of using the CDF and the integrated quantity is for mesh tallies<br>
./gun.sh: 2: ./gun.sh: source: not found
[2019-01-17 12:44:49 +0000] [23290] [INFO] Shutting down: Master
[2019-01-17 12:44:49 +0000] [23374] [INFO] Starting gunicorn 19.9.0
[2019-01-17 12:44:49 +0000] [23374] [INFO] Listening at: http://127.0.0.1:8000 (23374)
[2019-01-17 12:44:49 +0000] [23374] [INFO] Using worker: sync
[2019-01-17 12:44:49 +0000] [23378] [INFO] Booting worker with pid: 23378
[2019-01-17 12:46:47,870] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 12:46:48,873] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 15:45:51,360] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 15:45:53,462] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 15:46:10,185] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 15:46:20,283] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 15:46:21,747] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 15:46:34,958] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 15:46:51,993] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:20:47,586] ERROR in app: Exception on /update_title [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:21:02,129] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:21:31,942] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:21:45,908] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:21:56,696] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:22:23,891] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:22:28,615] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:22:52,467] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:23:47,083] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:23:50,669] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:24:15,014] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 16:30:49,286] ERROR in app: Exception on /update_line [POST]
Traceback (most recent call last):
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ubuntu/git/dotter/.env/local/lib/python2.7/site-packages/flask/app.py", line 1957, in make_response
    'The view function did not return a valid response. The'
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[2019-01-17 17:55:27 +0000] [23374] [INFO] Handling signal: hup
[2019-01-17 17:55:27 +0000] [23374] [INFO] Hang up: Master
[2019-01-17 17:55:27 +0000] [23755] [INFO] Booting worker with pid: 23755
